### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by asutrem** [zooxo/scott#2]
Hello, after I tried to compile the program, the IDE errored out saying that it overflowed the max memory of the ATtiny85. Below is the error code:

`Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld: attinycalc.ino.elf section `.text' will not fit in region `text'
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld: region `text' overflowed by 262 bytes
collect2: error: ld returned 1 exit status`

I also have the issue of the IDE complaining about multiple libraries.

`Multiple libraries were found for "TinyWireM.h"
 Used: /Users/yauwai/Documents/Arduino/libraries/TinyWireM
Multiple libraries were found for "EEPROM.h"
 Used: /Users/yauwai/Library/Arduino15/packages/ATTinyCore/hardware/avr/1.2.3/libraries/EEPROM
exit status 1
Error compiling for board ATtiny25/45/85.`

How do I solve this?

**Comment by zooxo** [comment]
Hello asutrem!
First let me thank you for your interest in trying Scott.

It is not so easy for me to interpret your error code but it seems that you have to configure your IDE to program ATTINYs.

* First you need to support ATTINY processors and install in FILE -> PREFERENCES  an appropriate package. I have added in "Additional Board Manager URLs": https://raw.githubusercontent.com/damellis/attiny/ide-1.6.x-boards-manager/packager_damellis_attiny_index.json

* You should see in your Arduino files: ../packages/attiny/hardware/avr/1.0.2 which contains some files like "boards.txt".

* Then you should be able to select in TOOLS -> BOARD -> ATtiny25/45/85 and TOOLS ->PROCESSOR -> ATtiny85 and TOOLS -> CLOCK -> Internal 8MHz.

* Finally burn a bootloader with TOOLS -> Burn Bootloader.

* This presumes that you have the appropriate hardware. I use an Arduino UNO as programmer.

* Then try to compile scott.ino with SKETCH -> Verify/Compile. The executable file should be very close to 8k (I used almost every byte available).


* Additionally it seems that you have 2 or more versions of TinyWire installed. I have in SKETCH -> INCLUDE LIBRARY -> MANAGE LIBRARIES only TinyWireM by Adafruit v1.0.0 installed. But this seems to be a warning of your IDE only ... it uses one of your libraries.

As I'm not an expert in configuring an IDE please see some appropriate tutorials on the internet.
A lot to tweak - good luck. 
deetee

**Comment by zooxo** [comment]
Ah sorry I made some typo providing the Additional Boards Manager - this seems to be correct:
https://raw.githubusercontent.com/damellis/attiny/ide-1.6.x-boards-manager/package_damellis_attiny_index.json

**Comment by asutrem** [comment]
Hello! I tried it again on another computer and it compiles with no problem. (P.S That is a large program size, it used 98% of the space!)

Thank you! 
asutrem

**Comment by zooxo** [comment]
Great!
And yes I used to use every byte well-considered to provide as much calculator for 8k as possible.
So far SCOTT is my every day desktop calculator - and the battery lasts very long.
Please keep me posted how your project is going on.
Regards
deetee
